

export const DOMES = {
    'ARI': true,
    'ATL': true,
    'BAL': false,
    'BUF': false,
    'CAR': false,
    'CHI': false,
    'CIN': false,
    'CLE': false,
    'DAL': true,
    'DEN': false,
    'DET': true,
    'GB': false,
    'HOU': true,
    'IND': true,
    'JAX': false,
    'KC': false,
    'LV': true,
    'LAC': true,
    'LAR': true,
    'MIA': false,
    'MIN': true,
    'NE': false,
    'NO': true,
    'NYG': false,
    'NYJ': false,
    'PHI': false,
    'PIT': false,
    'SF': false,
    'SEA': false,
    'TB': false,
    'TEN': false,
    'WAS': false,
}