export const TOOLTIPS = {
    SLOW_DRAFT: 'Slow Draft',
    INSTANT_DRAFT: 'Instant Draft',
    T_DRAFT: 'Tournament',
    G_DRAFT: 'Guaranteed',
    NFL_DRAFT: 'NFL',
    BB_DRAFT: 'Best Ball',
    WW_DRAFT: 'Weekly Winners',
    GRID_ERROR: 'Unable to find ADP data for this player. Please report this issue to the Twitter account linked in the footer',
    SELECTED_TYPE_DATA: 'Generated using data for the selected exposure type',
    ALL_TYPE_DATA: 'Calculated using all uploaded exposure data',
    DOME_GAME: 'Dome Game',
    TOTAL_CLV: 'Total Closing Line Value for Drafted Team. Closing Line Value for each player is calculated as follows: Pick Number - Average Draft Position',
    ADP: 'Average Draft Position',
    CLV: 'Closing Line Value: Pick Number - Average Draft Position',
    RESURRECTION: 'Resurrection is a best ball tournament which began on week 6 of the 2023 NFL season. The Resurrection ADPs reflect a player\'s perceived value through the first five weeks of the season.',
    DELETE_EXPOSURE: 'Delete exposure data',
    DELETE_DISABLED: 'Deletion Disabled',
}